export const USERS = [
  {
    id: "1",
    name: "Marcus Chen",
    role: "Alumni",
    university: "Stanford",
    location: "San Francisco, CA",
    avatar: "",
    skills: ["iOS Dev", "Swift", "Product Management", "Figma", "Go"],
    interests: ["Mobile", "Fintech", "Open Source"],
    bio: "iOS developer turned PM. Love mentoring and building impactful products.",
    matchScore: 94,
    year: "2022",
    connections: 1204,
    available: true,
    certifications: ["PMP", "Apple Developer"],
    projects: ["PayEasy App", "MentorLink"],
  },
  {
    id: "2",
    name: "Sofia Ramirez",
    role: "Student",
    university: "UC Berkeley",
    location: "Berkeley, CA",
    avatar: "https://images.unsplash.com/photo-1762522921456-cdfe882d36c3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    skills: ["JavaScript", "Node.js", "GraphQL", "React", "TypeScript"],
    interests: ["Web3", "Gaming", "AR/VR"],
    bio: "Full-stack dev exploring the intersection of gaming and blockchain.",
    matchScore: 82,
    year: "2026",
    connections: 156,
    available: false,
    certifications: ["Meta Frontend Developer"],
    projects: ["NFT Gallery", "GameFi Hub"],
  },
  {
    id: "3",
    name: "James Okafor",
    role: "Student",
    university: "Carnegie Mellon",
    location: "Pittsburgh, PA",
    avatar: "https://images.unsplash.com/photo-1701967341617-14499d8bf8c3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    skills: ["Cybersecurity", "Python", "Linux", "Network Security", "Rust"],
    interests: ["InfoSec", "Privacy", "CTF"],
    bio: "Security enthusiast building safer digital spaces for everyone.",
    matchScore: 79,
    year: "2025",
    connections: 312,
    available: true,
    certifications: ["CompTIA Security+", "CEH"],
    projects: ["SecureVault", "ThreatMap"],
  },
  {
    id: "4",
    name: "Priya Sharma",
    role: "Alumni",
    university: "Georgia Tech",
    location: "Atlanta, GA",
    avatar: "https://images.unsplash.com/photo-1573496782646-e8d943a4bdd1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    skills: ["Data Science", "SQL", "TensorFlow", "Tableau", "R"],
    interests: ["Healthcare AI", "Social Good", "Open Data"],
    bio: "Data scientist using ML to improve healthcare outcomes in underserved communities.",
    matchScore: 91,
    year: "2021",
    connections: 876,
    available: true,
    certifications: ["TensorFlow Developer", "IBM Data Science"],
    projects: ["HealthPredict", "OpenDataHub"],
  },
  {
    id: "5",
    name: "Liam Williams",
    role: "Recruiter",
    university: "N/A",
    location: "New York, NY",
    avatar: "https://images.unsplash.com/photo-1646579886741-12b59840c63f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    skills: ["Talent Acquisition", "Technical Recruiting", "HR Analytics"],
    interests: ["Diversity Hiring", "Tech Talent"],
    bio: "Tech recruiter at a Series B startup. Always looking for passionate builders.",
    matchScore: 73,
    year: "N/A",
    connections: 2340,
    available: true,
    certifications: [],
    projects: [],
  },
];

export const PROJECTS = [
  {
    id: "p1",
    title: "EduAI – Personalized Learning Platform",
    description: "An AI-powered adaptive learning system that customizes curriculum based on student performance and learning style.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
    skills: ["React", "Python", "ML", "Node.js"],
    team: [USERS[0], USERS[1]],
    status: "In Progress",
    members: 3,
    openRoles: ["Backend Dev", "Designer"],
    progress: 65,
    category: "EdTech",
  },
  {
    id: "p2",
    title: "ClimateTrack – Carbon Footprint Monitor",
    description: "Real-time carbon footprint tracker for universities, helping campuses achieve sustainability goals.",
    image: "https://images.unsplash.com/photo-1646579886741-12b59840c63f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
    skills: ["React Native", "IoT", "Data Viz", "Python"],
    team: [USERS[2], USERS[3]],
    status: "Open",
    members: 2,
    openRoles: ["IoT Engineer", "Data Analyst", "PM"],
    progress: 20,
    category: "Sustainability",
  },
  {
    id: "p3",
    title: "MedConnect – Healthcare Matching App",
    description: "Connecting medical students with volunteer opportunities at clinics and hospitals across the US.",
    image: "https://images.unsplash.com/photo-1762341119237-98df67c9c3c9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
    skills: ["Flutter", "Firebase", "Node.js", "GraphQL"],
    team: [USERS[4]],
    status: "Open",
    members: 1,
    openRoles: ["Flutter Dev", "UX Designer", "Backend"],
    progress: 10,
    category: "Healthcare",
  },
  {
    id: "p4",
    title: "SecureVault – End-to-End Encrypted Notes",
    description: "A zero-knowledge encrypted note-taking app with biometric authentication for students.",
    image: "https://images.unsplash.com/photo-1762158007836-25d13ab34c1c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
    skills: ["Rust", "Cryptography", "React", "WebAssembly"],
    team: [USERS[3], USERS[0]],
    status: "Completed",
    members: 4,
    openRoles: [],
    progress: 100,
    category: "Security",
  },
  {
    id: "p5",
    title: "CampusHire – Student Job Portal",
    description: "Skill-first job portal connecting students directly with startups based on projects and skills, not GPA.",
    image: "https://images.unsplash.com/photo-1573496782646-e8d943a4bdd1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
    skills: ["Next.js", "PostgreSQL", "TypeScript", "TailwindCSS"],
    team: [USERS[1], USERS[2]],
    status: "In Progress",
    members: 5,
    openRoles: ["Marketing", "ML Engineer"],
    progress: 45,
    category: "Career",
  },
];

export const MENTORS = [
  {
    id: "m1",
    name: "Dr. Sarah Mitchell",
    title: "Senior ML Engineer",
    company: "Google DeepMind",
    avatar: "https://images.unsplash.com/photo-1573496782646-e8d943a4bdd1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    skills: ["Machine Learning", "TensorFlow", "Python", "Research"],
    rating: 4.9,
    reviews: 47,
    sessions: 120,
    availability: "Weekends",
    bio: "10+ years in AI research. Former professor. Love helping students break into ML.",
    topics: ["Career Transition", "ML Research", "Interview Prep"],
    price: "Free",
    university: "Stanford PhD",
  },
  {
    id: "m2",
    name: "Marcus Chen",
    title: "Product Manager",
    company: "Stripe",
    avatar: "",
    skills: ["Product Strategy", "iOS", "Go-to-Market", "User Research"],
    rating: 4.8,
    reviews: 32,
    sessions: 88,
    availability: "Evenings",
    bio: "Shipped 3 products from 0 to 1M users. Happy to help with PM transitions.",
    topics: ["Product Management", "Startup Advice", "Career Switch"],
    price: "Free",
    university: "Stanford CS Alumni",
  },
  {
    id: "m3",
    name: "Priya Sharma",
    title: "Data Scientist",
    company: "NIH",
    avatar: "https://images.unsplash.com/photo-1563290329-f80d8464a6ab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    skills: ["Data Science", "Healthcare AI", "R", "Statistics"],
    rating: 4.7,
    reviews: 28,
    sessions: 65,
    availability: "Flexible",
    bio: "Passionate about using data for social good. Open to mentoring underrepresented students.",
    topics: ["Data Science", "Research Methods", "Social Impact"],
    price: "Free",
    university: "Georgia Tech Alumni",
  },
  {
    id: "m4",
    name: "Alex Thompson",
    title: "CTO & Co-founder",
    company: "BuildWithAI",
    avatar: "https://images.unsplash.com/photo-1762158007836-25d13ab34c1c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    skills: ["Entrepreneurship", "System Design", "Fundraising", "Leadership"],
    rating: 4.9,
    reviews: 61,
    sessions: 200,
    availability: "Bi-weekly",
    bio: "Serial founder. 2 exits. Here to help ambitious students build real companies.",
    topics: ["Startup Building", "Fundraising", "Technical Leadership"],
    price: "Free",
    university: "MIT Alumni",
  },
];

export const NOTIFICATIONS = [
  { id: "n1", type: "connection", message: "Sofia Ramirez sent you a connection request", time: "2m ago", read: false, avatar: "https://images.unsplash.com/photo-1762522921456-cdfe882d36c3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=100" },
  { id: "n2", type: "collaboration", message: "You've been invited to join EduAI Platform", time: "1h ago", read: false, avatar: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=100" },
  { id: "n3", type: "endorsement", message: "James Okafor endorsed your Python skills", time: "3h ago", read: true, avatar: "https://images.unsplash.com/photo-1701967341617-14499d8bf8c3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=100" },
  { id: "n4", type: "mentorship", message: "Dr. Sarah Mitchell accepted your mentorship request", time: "1d ago", read: true, avatar: "https://images.unsplash.com/photo-1573496782646-e8d943a4bdd1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=100" },
  { id: "n5", type: "opportunity", message: "New role matching your skills: Frontend Engineer at Stripe", time: "2d ago", read: true, avatar: null },
];

export const CONVERSATIONS = [
  {
    id: "c1",
    user: USERS[0],
    lastMessage: "Hey! Would love to collaborate on the EduAI project. Your ML skills would be perfect!",
    time: "2m ago",
    unread: 2,
    messages: [
      { id: "msg1", sender: "them", text: "Hey! I saw your profile — your ML work is impressive.", time: "10:30 AM" },
      { id: "msg2", sender: "me", text: "Thanks Marcus! I've been following your iOS projects too. Really clean design.", time: "10:32 AM" },
      { id: "msg3", sender: "them", text: "I'm building a new EdTech product and need someone with your skills. Want to chat?", time: "10:35 AM" },
      { id: "msg4", sender: "them", text: "Hey! Would love to collaborate on the EduAI project. Your ML skills would be perfect!", time: "10:45 AM" },
    ],
  },
  {
    id: "c2",
    user: USERS[3],
    lastMessage: "The data pipeline is almost ready. Check the PR when you get a chance.",
    time: "1h ago",
    unread: 0,
    messages: [
      { id: "msg5", sender: "them", text: "Working on the HealthPredict feature. Almost done!", time: "9:00 AM" },
      { id: "msg6", sender: "me", text: "Awesome! Can't wait to see it. Need any help?", time: "9:05 AM" },
      { id: "msg7", sender: "them", text: "The data pipeline is almost ready. Check the PR when you get a chance.", time: "9:30 AM" },
    ],
  },
  {
    id: "c3",
    user: USERS[2],
    lastMessage: "Sure! Let's connect at the virtual hackathon next week.",
    time: "3h ago",
    unread: 1,
    messages: [
      { id: "msg8", sender: "me", text: "Hi Sofia! I loved your NFT Gallery project. Really creative stuff!", time: "Yesterday" },
      { id: "msg9", sender: "them", text: "Thanks! I've been working on it for months. Are you into Web3?", time: "Yesterday" },
      { id: "msg10", sender: "me", text: "Somewhat! Would love to learn more. Maybe collaborate?", time: "Yesterday" },
      { id: "msg11", sender: "them", text: "Sure! Let's connect at the virtual hackathon next week.", time: "Yesterday" },
    ],
  },
];

export const OPPORTUNITIES = [
  { id: "o1", title: "ML Engineering Intern", company: "Google", type: "Internship", skills: ["Python", "TensorFlow", "ML"], location: "Mountain View, CA", deadline: "Mar 15, 2026", logo: "G" },
  { id: "o2", title: "Frontend Developer", company: "Stripe", type: "Full-time", skills: ["React", "TypeScript", "CSS"], location: "Remote", deadline: "Mar 30, 2026", logo: "S" },
  { id: "o3", title: "Data Science Co-op", company: "Meta", type: "Co-op", skills: ["Python", "SQL", "Statistics"], location: "Menlo Park, CA", deadline: "Apr 1, 2026", logo: "M" },
  { id: "o4", title: "iOS Developer Intern", company: "Apple", type: "Internship", skills: ["Swift", "UIKit", "Xcode"], location: "Cupertino, CA", deadline: "Apr 15, 2026", logo: "A" },
];

export const SKILL_OPTIONS = [
  "Python", "JavaScript", "TypeScript", "React", "Node.js", "Machine Learning",
  "Data Science", "UI/UX Design", "Figma", "Swift", "Kotlin", "Flutter",
  "Go", "Rust", "GraphQL", "SQL", "AWS", "Docker", "Kubernetes",
  "TensorFlow", "PyTorch", "Cybersecurity", "Blockchain", "Product Management",
  "Data Analysis", "R", "Tableau", "iOS Dev", "Android Dev", "Next.js",
  "Vue.js", "Django", "FastAPI", "PostgreSQL", "MongoDB", "Redis", "Unity",
];

export const INTEREST_OPTIONS = [
  "AI / Machine Learning", "Web Development", "Mobile Apps", "Cybersecurity",
  "Data Science", "Blockchain / Web3", "Gaming", "AR / VR", "EdTech",
  "HealthTech", "Fintech", "Sustainability", "Social Impact", "Open Source",
  "Startups", "Research", "Design", "Product", "Hardware / IoT", "Space Tech",
];

export const RECRUITER_STATS = {
  totalCandidates: 1847,
  savedCandidates: 43,
  activeOpportunities: 6,
  applicationsReceived: 312,
  avgMatchScore: 84,
  topSkillsNeeded: [
    { skill: "React", demand: 87 },
    { skill: "Python", demand: 82 },
    { skill: "Machine Learning", demand: 79 },
    { skill: "TypeScript", demand: 74 },
    { skill: "Node.js", demand: 68 },
    { skill: "Data Science", demand: 65 },
    { skill: "Cybersecurity", demand: 58 },
    { skill: "Flutter", demand: 52 },
  ],
};